stages:
  - trigger


trigger-frontend:
  stage: trigger
  trigger:
    include: 
      ./pipelines/frontend.yml
    strategy: depend
  rules:
    - changes:
        - spotify-front/**/*

trigger-backend:
  stage: trigger
  trigger:
    include:
      ./pipelines/backend.yml
    strategy: depend
  rules:
    - changes:
        - spotify-back/**/* 

