
image: sleavely/node-awscli:22.x

stages:
  - build
  - push_to_s3
  # - invalidate_cache

build:
  stage: build
  script:
    - cd spotify-front
    - npm install
    - npm run build
  artifacts:
    paths:
      - spotify-front/dist
  rules:
    - changes:
        - spotify-front/**/*
    

push-to-s3:
  stage: push_to_s3
  script:
    - ls 
    - cd spotify-front
    - ls
    - aws s3 sync ./dist/ s3://spotify-frontend-marij --delete
  needs: ["build"]

# invalidate-cache:
#   stage: invalidate_cache
#   script:
#     - aws cloudfront create-invalidation --distribution-id E3LCVX33WASGDD --paths "/*"
#   needs: ["push-to-s3"]
