stages:
  - trigger


trigger-frontend:
  stage: trigger
  trigger:
    include: 
      ./pipelines/frontend.yml
    strategy: depend
  rules:
    - changes:
        - spotify-front/**/*

trigger-song-service:
  stage: trigger
  trigger:
    include:
      ./pipelines/song-service.yml
    strategy: depend
  rules:
    - changes:
        - ./services/song-service/**/*

