#frontend
image: sleavely/node-awscli:22.x

stages:
  - build
  - push_to_s3
  - invalidate_cache

build:
  stage: build
  script:
    - cd spotify-front
    - npm install
    - npm run build
  artifacts:
    paths:
      - spotify-front/dist
  rules:
    - changes:
        - spotify-front/**/*
    

push-to-s3:
  stage: push_to_s3
  script:
    - cd spotify-front
    - aws s3 sync ./dist/ s3://spotify-frontend-marij --delete
  rules:
    - changes:
        - spotify-front/**/*
  needs: ["build"]

invalidate-cache:
  stage: invalidate_cache
  script:
    - aws cloudfront create-invalidation --distribution-id E3LCVX33WASGDD --paths "/*"
  rules:
      - changes:
          - spotify-front/**/* 
  needs: ["push-to-s3"]
