stages:
  - dockerize
  - update_helm

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: marijahmed/spotify-admin-service

build_docker_image:
  image: docker:24.0.5
  services:
  - docker:24.0.5-dind
  stage: dockerize
  script:
    - cd services/admin-service
    - docker build -t $IMAGE_NAME:${CI_COMMIT_SHORT_SHA} .
    - echo "$DOCKERHUB_TOKEN" | docker login -u "marijahmed" --password-stdin
    - docker push $IMAGE_NAME:${CI_COMMIT_SHORT_SHA}

github_clone:
  image: marijahmed/alpine-git-yq:latest
  stage: update_helm
  script:
    - set -e
    - git config --global user.name "Marijahmedd"
    - git config --global user.email "muhammadmarijahmed@gmail.com"
    - git clone https://${GITHUB_TOKEN}@github.com/Marijahmedd/spotify-microservices.git
    - cd spotify-microservices
    - yq -i '.images.spotifyAdminService.tag = "'${CI_COMMIT_SHORT_SHA}'"' helm/spotify-services/values.yaml
    - git add helm/spotify-services/values.yaml
    - git commit -m "Update admin service image tag to ${CI_COMMIT_SHORT_SHA}"
    - git push origin main