stages:
  - build
  - push_to_s3
  - invalidate_cache

image: sleavely/node-awscli:22.x

build:
  stage: build
  script:
    - cd spotify-front
    - npm install
    - npm run build
  rules:
    - changes:
        - spotify-front/**/*

push-to-s3:
  stage: push_to_s3
  script:
    - aws s3 sync ./spotify-front/dist/ s3://spotify-frontend-marij --delete
  rules:
    - changes:
        - spotify-front/**/*

invalidate-cache:
  stage: invalidate_cache
  script:
    - aws cloudfront create-invalidation --distribution-id E3LCVX33WASGDD --paths "/*"
  rules:
    - changes:
        - spotify-front/**/*
