stages:
  - dockerize
  - push_to_dockerhub

image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: marijahmed/spotify-song-service

before_script:
  - docker info

build_docker_image:
  stage: dockerize and push
  script:
    - cd services/song-service
    - echo "$DOCKERHUB_TOKEN" | docker login -u "marijahmed" --password-stdin
    - docker build -t $IMAGE_NAME:${CI_COMMIT_SHORT_SHA} .
    - docker push $IMAGE_NAME:${CI_COMMIT_SHORT_SHA}


