stages:
  - dockerize
  - push to docker hub

image: docker:24.0.5
services:
  - docker:24.0.5-dind
before_script:
  - docker info
variables:
  DOCKER_TLS_CERTDIR: "/certs"

Build Docker Image:
  stage: dockerize
  script:
    - cd services/song-service
    - docker build -t spotify-song-service:${CI_COMMIT_SHORT_SHA} .

Push Docker Image:
  stage: push to docker hub
  needs: [Build Docker Image]
  script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "marijahmed" --password-stdin
    - docker push spotify-song-service:${CI_COMMIT_SHORT_SHA}

