stages:
  - dockerize

image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: marijahmed/spotify-song-service


build_docker_image:
  stage: dockerize
  script:
    - cd services/song-service
    - docker build -t $IMAGE_NAME:${CI_COMMIT_SHORT_SHA} .
    - echo "$DOCKERHUB_TOKEN" | docker login -u "marijahmed" --password-stdin
    - docker push $IMAGE_NAME:${CI_COMMIT_SHORT_SHA}
