apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-service-deployment
  namespace: spotify
  labels:
    app: song-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: song-service
  template:
    metadata:
      labels:
        app: song-service
    spec:
      containers:
      - name: song-service-container
        image: marijahmed/spotify-song-service:latest
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "700Mi"
            cpu: "700m"
        ports:
        - containerPort: 7000
        envFrom:
        - secretRef:
            name: song-service-secret
        - secretRef:
            name: shared-secret
