apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  namespace: spotify
data:
  BASE_URL: aHR0cHM6Ly9zcG90aWZ5Lm1hcmlqLm1l
  PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxYXREbWFGYjBMSE83UHRDUVp1RAoxa0tleW5TNjZTbTBabWN5eDZscDl6SUlHM2RhWnhjaFFlejU2RFBEeGVwdFg3THZOQTd3MWN2Ylk4VHc0S3ZMCk5qdjlTcVAyVkJpQVZhZlRuaHpiVU1zNHUvY0lSSlNmNmRMU1Q1MnZoeFEwYUlTc21YWG9vbkd1OVNSR1FlRTIKbWhabVhMN01tZFNsYzlwdFJmUGgyMXQ1ZG1VTjgrUUtHd0hwZHpHN3pWVmVWOWwyTFBkUURJRWZKTExVeFBGQwpaLzI3aHNTUjVnWXlGMTFpQ2FMQzY4UFFqbHoydzVtRGtMZndvSzFZK0VVb1FhVGtrTDA2cXJLQmxjcW1CSENTCng3b1ZpUmR5Nk5kZlZqVHhuYmR0TGlmQ3E3MHBOZHgyVmhKd2JremNLVmpnajczYkVOekNIR3d0TW5mbC9veVAKVVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
